# Automapper configuration
# [templates.example_template] - example_template should be replaced with the name of your map template.
# directory - The direct path to our map files.
# map_files - These are the names of the map files, including the extension, that will be loaded. Supports multiple for randomness.
# required_map - This is the name of the required map that needs to be loaded in order for this template to load.
# coordinates - The coordinates of the map template placement. (X, Y, Z). PLEASE NOTE: The Z coordinate is the same as would be shown in SDMM. NOT IN GAME.
# leave it at 1 if it is not a multi-z map. It is relative to the map file Z, not the one loaded in game.
# trait_name - The name of the Z level trait that will be used to determine what Z level we use.
# Traits - Station (for station relatied edits), CentCom (for edits on the CC map), Mining (for edits on Lavaland)
# More can be found in code\__DEFINES\maps.dm

# Metastation Cryo
# [templates.metastation_cryo]
# map_files = ["metastation_cryo.dmm"]
# directory = "_maps/bandastation/automapper/templates/metastation/"
# required_map = "MetaStation.dmm"
# coordinates = [133, 182, 1]
# trait_name = "Station"

# CentCom Crew Quarters
[templates.CentCom_kekypaj]
map_files = ["CentCom.dmm"]
directory = "_maps/bandastation/automapper/templates/centcom/"
required_map = "builtin"
coordinates = [12, 53, 1]
trait_name = "CentCom"

# CentCom NAS Trurl
[templates.CentCom_Trurl]
map_files = ["Trurl.dmm"]
directory = "_maps/bandastation/automapper/templates/centcom/"
required_map = "builtin"
coordinates = [133, 006, 1]
trait_name = "Trurl"

# DeltaStation
[templates.deltastation_lawyer_office]
map_files = ["deltastation_lawyer_office.dmm"]
directory = "_maps/bandastation/automapper/templates/deltastation/"
required_map = "DeltaStation2.dmm"
coordinates = [123, 143, 1]
trait_name = "Station"

[templates.deltastation_magistrate_office]
map_files = ["deltastation_magistrate_office.dmm"]
directory = "_maps/bandastation/automapper/templates/deltastation/"
required_map = "DeltaStation2.dmm"
coordinates = [185, 122, 1]
trait_name = "Station"

[templates.deltastation_ntr_blueshield_office]
map_files = ["deltastation_ntr_blueshield_office.dmm"]
directory = "_maps/bandastation/automapper/templates/deltastation/"
required_map = "DeltaStation2.dmm"
coordinates = [146, 108, 1]
trait_name = "Station"

# MetaStation
[templates.metastation_lawyer_office]
map_files = ["metastation_lawyer_office.dmm"]
directory = "_maps/bandastation/automapper/templates/metastation/"
required_map = "MetaStation.dmm"
coordinates = [57, 119, 1]
trait_name = "Station"

[templates.metastation_magistrate_office]
map_files = ["metastation_magistrate_office.dmm"]
directory = "_maps/bandastation/automapper/templates/metastation/"
required_map = "MetaStation.dmm"
coordinates = [119, 151, 1]
trait_name = "Station"

[templates.metastation_ntr_blueshield_office]
map_files = ["metastation_ntr_blueshield_office.dmm"]
directory = "_maps/bandastation/automapper/templates/metastation/"
required_map = "MetaStation.dmm"
coordinates = [101, 115, 1]
trait_name = "Station"

# IceBoxStation
[templates.iceboxstation_blueshield_office]
map_files = ["iceboxstation_blueshield_office.dmm"]
directory = "_maps/bandastation/automapper/templates/iceboxstation/"
required_map = "IceBoxStation.dmm"
coordinates = [99, 154, 3]
trait_name = "Station"

[templates.iceboxstation_detective_office]
map_files = ["iceboxstation_detective_office.dmm"]
directory = "_maps/bandastation/automapper/templates/iceboxstation/"
required_map = "IceBoxStation.dmm"
coordinates = [86, 161, 2]
trait_name = "Station"

[templates.iceboxstation_magistrate_office]
map_files = ["iceboxstation_magistrate_office.dmm"]
directory = "_maps/bandastation/automapper/templates/iceboxstation/"
required_map = "IceBoxStation.dmm"
coordinates = [99, 150, 2]
trait_name = "Station"

[templates.iceboxstation_ntr_office]
map_files = ["iceboxstation_ntr_office.dmm"]
directory = "_maps/bandastation/automapper/templates/iceboxstation/"
required_map = "IceBoxStation.dmm"
coordinates = [92, 147, 2]
trait_name = "Station"

# TramStation
[templates.tramstation_detective_office]
map_files = ["tramstation_detective_office.dmm"]
directory = "_maps/bandastation/automapper/templates/tramstation/"
required_map = "tramstation.dmm"
coordinates = [82, 126, 2]
trait_name = "Station"

[templates.tramstation_magistrate_lawyer_office]
map_files = ["tramstation_magistrate_lawyer_office.dmm"]
directory = "_maps/bandastation/automapper/templates/tramstation/"
required_map = "tramstation.dmm"
coordinates = [107, 142, 1]
trait_name = "Station"

[templates.tramstation_ntr_blueshield_office]
map_files = ["tramstation_ntr_blueshield_office.dmm"]
directory = "_maps/bandastation/automapper/templates/tramstation/"
required_map = "tramstation.dmm"
coordinates = [79, 130, 2]
trait_name = "Station"
